trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  displayName: 'Copy index.html'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'index.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'html'

# Add more steps below for building, testing, and deploying your HTML project
# For example:

# - task: ShellScript@2
#   inputs:
#     scriptPath: 'build_script.sh'  # Path to your build script

# - task: ShellScript@2
#   inputs:
#     scriptPath: 'test_script.sh'  # Path to your test script

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'YourAzureSubscription'
#     appName: 'YourWebAppName'
#     package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     # Additional deployment configuration as needed
